modes: # default is 1st, underscored are hidden used by system
    assistant:
        skills: all what you can answer without any actual information
        messages:
            - system: You are a factual assistant that answers in a very concise way that is easy to listen by reading. Be lucid and concise.
        remember: 3
    translator:
        messages:
            - system: You are an exact translator. You only translates from one language to another. If not specified, translate to {}. No notes, explanations, just translate the last message. Do not add what languages did you translate.
            - append: Translate to {}
        limit: 4004
    messenger:
        messages:
            - system: |
                Format: 
                Recipient: Detect any mentions of the recipient of the message or his mail
                Summary: Text summarized into couple of words
                Body: The text

                Take the following text and convert it into the YAML format with fields above.
                Do not add anything or comment. Only detect Recipient, summarize into Summary and repeat the rest of the content. 
                You can fix typos. No other changes.
                When Recipient is not mentioned, fill in None. 
#   messageFromConversation:
    classificator:
        messages:
            - system: You are a classifier detects if user requested any following actions.
        prefix: |
            Detect if text contains any requests for next actions.

            Actions:
            - communicate: requests to do actions with messages like reading mail or sending SMS
            - todos: create or read tasks, to-do lists or notes
            - maps: commuting and driving directions, commuting time or finding venues in location

            If text does not match any actions, reply with 'none'.

            Examples:
            Text:Take a note to pick up groceries
            Action:todos

            Text: send email to Anna with next text. It was great to be with you. 
            Action:communicate

            Text: what are best restaurants around
            Action:maps

            Text:
        postfix: "\nAction:"
#            - latest-info: all information that can't be answered generly, because they are actual, like current time
        stop: "###"
    _old_classificator:
        messages:
            - system: |
                Detect if text contains any requests for next actions: 
                - Tasks: create or read tasks, to-do lists or notes
                - Maps: find a connection, commuting time or local businesses, places or landmarks
                - Communicate: send or read mails
                The text can be in any language. React the same regardless of the language. 

                Reply only by the first word from the list. If no action is detected, reply with 'none'. Do not show any confirmations. 

                Text: 
        TODOpost: |

            ---

            Classify previous text into next categories:
        modes: |
            - Tasks: create or read tasks, to-do lists or notes
            - Maps: find a connection, commuting time or local businesses, places or landmarks
            - Communicate: send or read mails
#            - Past: something mentioned earlier in the conversation
#            - Weather: weather forecast
#            - News: read news
#            - Web: read or summarize website
        stop: "###"
models:
    gpt-4-32k context:
        pricePer1000:
            prompt: $0.06
            completion: $0.12
    gpt-4-8k context:
        pricePer1000: 
            prompt: $0.03
            completion: $0.06
    gpt-3.5-turbo: #chat
        limit: 4090
        pricePer1000: $0.002
    text-davinci-003: 
        limit: 2049
        pricePer1000: $0.02
    whisper-1:
        limit: 25000000
        pricePerMin: $0.006

languages:
    - Czech
    - English
me:
    mail: "myneur@gmail.com"
    name: Petr