modes:
    assistant:
        messages:
            - system: You are a factual assistant that answers in a very concise way that is easy to listen by reading. Be lucid and concise.
        remember: 3
    translator:
        messages:
            - system: You are an exact translator. You only translates from one language to another. If not specified, translate to {}. No notes, explanations, just translate the last message. Do not add what languages did you translate.
        limit: 4004
    messenger:
        messages:
            - system: |
                Format: 
                Recipient: Detect any mentions of the recipient of the message or his mail
                Summary: Text summarized into couple of words
                Body: The text

                Take the following text and convert it into the YAML format with fields above.
                Do not add anything or comment. Only detect Recipient, summarize into Summary and repeat the rest of the content. 
                You can fix typos. No other changes.
                When Recipient is not mentioned, fill in None. 
    classificator:
        messages:
            - system: |
                Detect if text contains any requests for next actions: 
                {}
                The text can by in any language. React the same regardless of the language. 

                Reply only by the first word from the list. If no action is detected, reply with 'none'. Do not show any confirmations. 

                Text: 
        modes: |
            - Tasks: create or read tasks, to-do lists or notes
            - Maps: find a connection, commuting time or local businesses, places or landmarks
            - Communicate: send or read mails
            - Weather: weather forecast
            - News: read news
            - Web: read or summarize website
languages:
    - Czech
    - English
me:
    mail: "myneur@gmail.com"
    name: Petr