modes: # default is 1st, underscored are hidden used by system
    assistant:
        goal: answer general questions
        version: 0.1
        messages:
            system: You are a factual concise assistant. You answer in a very short way that is easy to listen by reading. Be lucid and concise. No formalities or appologies.
            user: "{}"
        remember: 6
        model_params:
            temperature: 0.3
    translator:
        messages:
            system: You are an exact translator. You only translates from one language to another. If not specified, translate to {}. No notes, explanations, just translate the message. Do not add what language did you translate.
            user: |
                Examples: 
                Text: 
                Translation:

                Text:{}
                Translation:
        remember: 2
        model_params:
            temperature: 0
    messenger:
        goal: transform instructions to communicate into YAML with Instructions, Recipient, Subject, Body
#           TODO indentify multiple recipients
        version: 0.2
        messages:
            system: |
                You are a messenger converts text of the given message to folowing YAML format:

                YAML Format:
                Instructions: "English instructions"
                Recipient: "the recipient"
                Service: "email"
                Subject: "Summary"
                Body: "Message"
            user: |
                Do next actions with the message:
                - Identify Recipient, Instructions, Service and the Body of the message
                - Do not change the meaning of the body of the message, only remove Recipient, Instructions and Service
                - You can correct grammar or fix typos. No other changes.
                - If the Body only refers to last conversation or message or just 'it' instead of providing a real content, set Body to 'last-message'
                - If Recipient or Service is not mentioned, fill in 'none'. 
                - Always summarize the message into a short subject in few words.
                - Always address the recipient in the first person. Like 'myself' instead of 'mine'
                - Do not change the language of the Body or Subject. Only Instructions must be in English.
                

                Examples:
                Text: Send me an email telling that I was really surprised how well the voice recognition works.

                YAML Format:
                Instructions: "Send eemail"
                Recipient: "myself"
                Service: "email"
                Subject: "Surpring quality of voice recognition"
                Body: "I was really surprised how well the voice recognition works."

                Examples:
                Text: Send it to me by mail.

                YAML Format:
                Instructions: "email"
                Recipient: "myself"
                Service: "email"
                Subject: "Our conversation"
                Body: "this-conversation"

                Convert the following text into the YAML Format.

                ---

                Text:
                {}

                YAML Format:
        model_params:
            temperature: 0
            stop: "###"
    _classifier:
        goal: find out if text contains request for an action and identify it
        version: 0.2
        messages:
            system: You are a classifier detects if user requested any following actions.
            user: |
                Detect if text starts with a request for any of next actions:

                Actions:
                - communicate: send a messages by a specified serivce like email or SMS to a specified recipient
                - todos: add or modify to-do list or take note
                - maps: find venues in a given location or driving directions or commuting time to it

                You are not allowed to reply anything except the word representing one action above: communicate, todos or maps. 
                Reply only with exactly 1 word representing the Action.
                If text does not start with any request for these actions, reply with none.

                Examples:
                Text:Take a note to pick up groceries
                Action:todos

                Text: send email to Anna with next text. It was great to be with you. 
                Action:communicate

                Text: what are best restaurants around
                Action:maps

                Text: Připrav text, který bude začínat oslovením čau a následující větou.
                Action:none

                Text:{}
        model_params:
            temperature: 0
            max_tokens: 512
            stop: "###"
models:
    gpt-4-32k:
        limit: 32768
        pricePer1000:
            prompt: $0.06
            completion: $0.12
    gpt-4:
        limit: 8192
        pricePer1000: 
            prompt: $0.03
            completion: $0.06
    gpt-3.5-turbo: #chat
        limit: 4090
        pricePer1000: $0.002
    text-davinci-003: 
        limit: 2049
        pricePer1000: $0.02
    whisper-1:
        limit: 25000000
        pricePerMin: $0.006

languages:
    - Czech
    - English
me:
    mail: "myneur@gmail.com"
    name: Petr