modes: # default is 1st, underscored are hidden used by system
    concise:
        goal: Answer general questions with easy to read replies
        version: 0.2
        messages:
            system: You are a concise assistant that answers in a way that is easy to listen by reading. No formalities or appologies.
            user: "{}"
            remember: 6
    assistant:
        goal: Answer general questions
        version: 0.1
        messages:
            system: You are a helpful assistant.
            user: "{}"
            remember: 6
    creative:
        goal: Come up with creative ideas
        version: 0.1
        messages:
            system: You are a creative that comes up with ideas on the given topic.
            user: "{}"
            remember: 6
        model_params:
            temperature: 1
    translator:
        goal: Efficient interpreter who translates from one language to another without comments.
        version: 0.2
        messages:
            system: |
                You are an accurate translator.
                - Translate between last 2 languages used.
                - If there was just 1 language used previously, translate to the other language from ({}).
                - No notes, explanations.
                - Do not mention what language did you translate to. 
                - Do not repeat the request for the translation.
            user: |
                Example:
                Text: Translate to French. Nice to meet you. 
                Translation: Le français est une très belle langue.

                Translate following text.

                Text:{}
                Translation:
            remember: 2
        model_params:
            temperature: 0
    writer:
        goal: Write text exactly as requested with corrected grammar
        version: 0.2
        messages: 
            system: |
                Help me preparing text by repeating it exacly as I send it.
                - Don't add anything. Not even a subject for mails. No comments. Do not elaborate. 
                - Keep the meaning unchanged.
                - correct grammar and typos.
            user: |
                Text:{}

                Remove starting request to write or prepare text or mail and repeat the rest with corrected typos as is.
        model_params:
            temperature: 0
    messenger:
        goal: transform instructions to communicate into YAML with Instructions, Recipient, Subject, Body
#           TODO indentify multiple recipients
        version: 0.2
        messages:
            system: |
                You are a messenger that converts text of the given message to folowing YAML format:

                YAML Format:
                Instructions: "English instructions"
                Recipient: "the recipient"
                Service: "email"
                Subject: "Summary"
                Body: "Message"
            user: |
                Do next actions with the message:
                - Identify Recipient, Instructions, Service and the Body of the message
                - Do not change the meaning of the body of the message, only remove Recipient, Instructions and Service
                - You can correct grammar or fix typos. No other changes.
                - If the Body only refers to last conversation or message or just 'it' instead of providing a real content, set Body to 'last-message'
                - If Recipient or Service is not mentioned, fill in 'none'. 
                - Always summarize the message into a short subject in few words.
                - Always address the recipient in the first person. Like 'myself' instead of 'mine'
                - Do not change the language of the Body or Subject. Only Instructions must be in English.
                

                Examples:
                Text: Send me an email telling that I was really surprised how well the voice recognition works.

                YAML Format:
                Instructions: "Send email"
                Recipient: "myself"
                Service: "email"
                Subject: "Surpring quality of voice recognition"
                Body: "I was really surprised how well the voice recognition works."

                Examples:
                Text: Send it to me by mail.

                YAML Format:
                Instructions: "Send email"
                Recipient: "myself"
                Service: "email"
                Subject: "Our conversation"
                Body: "this-conversation"

                Convert the following text into the YAML Format.

                ---

                Text:
                {}

                YAML Format:
        model_params:
            temperature: 0
            stop: "###"
    _pohádkobot:
        goal: Tell children fairy tales according to their wishes
        version: 0.1
        messages:
            system: Jsi pohádkový robot. Vyprávíš pohádky dětem na jejich přání. Pokud není řečeno jinak, vymysli pohádku přibližně o sedmi odstavcích.
            user: "{}"
    _classifier:
        goal: find out if text contains request for an action and identify it
        version: 0.2
        messages:
            system: You are a classifier that detects whether the user has requested any following actions.
            user: |
                Detect if text starts with a request for any of the next actions:

                Actions:
                - communicate: direct request to send the last message or just 'it' by a message, mail or text.
                - write: write a mail with the given text
                - inbox: read or summarize my inbox
                - calendar: schedule a meeting, or send  ameeting request
                - todos: add or modify a to-do list or take a note
                - maps: find venues in a given location or get driving directions or commuting time to a location
                - command: max few words starting with synonyms of (be, become)

                You are not allowed to reply anything except the word representing one action above: communicate, todos or maps. 
                Reply only with exactly 1 word representing the Action.
                If text does not start with a request for any of these actions, reply with none.

                Examples:
                Text: What's in my inbox?
                Action: inbox

                Text: Take a note to pick up groceries
                Action: todos

                Text: Send it to me by an email.
                Action: communicate

                Text: What are best restaurants around?
                Action: maps

                Text: Připrav text, který bude začínat oslovením čau a následující větou.
                Action: none

                Text: be my assistant.
                Action: command

                Text: be a translator.
                Action: command

                Text: {}
                Action: 
        model_params:
            temperature: 0
            max_tokens: 512
            stop: "###"
    _commander:
        goal: find out if an inquiry contains any request for an action and identify it
        version: 0.3
        messages:
            system: You are a classifier that detects whether the given inquiry starts with a request to perform a direct action.
            user: |
                Detect whether the following inquiry starts with a direct request to do something by a chosen service or means.

                Example:
                Request for action : create, read, update, delete, transform, get, draft, find, write, how long is or prepare
                Service or means: email, meeting, calendar, inbox, note, todo, maps, directions, commute, internet, call

                Text:{}
        model_params:
            temperature: 0
            max_tokens: 512
            stop: "###"
models:
    voice:
        whisper-1:
            limit: 25000000
            pricePerMin: 0.006
    chat:
        gpt-3.5-turbo: #chat
            limit: 4090
            pricePer1000: 0.002
        gpt-4:
            limit: 8192
            pricePer1000: 
                prompt: 0.03
                completion: 0.06
    _gpt-4-32k:
            limit: 32768
            pricePer1000:
                prompt: 0.06
                completion: 0.12
    completion:
        text-davinci-003: 
            limit: 2049
            pricePer1000: 0.02
languages:
    - Czech
    - English
me:
    mail: "petr@sl8.ch"
    name: Petr